### ISSUE TITLE
issues with some graphs

### ISSUE THREAD

**Issue by mritzmann** [HeadTalker/uptime-robot#1]
```
Warning: array_reverse() expects parameter 1 to be array, null given in /home/httpd/vhosts/status.markus-mail.com/status.markus-mail.com/main/index.php on line 214
```

Some graphs her has problems:
http://status.markus-mail.com/

Assumption: trouble with monitor type `HTTP(s)`?

**Comment by HeadTalker** [comment]
Thanks digging into it now

**Comment by HeadTalker** [comment]
@mritzmann Can you add this and see if there is any response times for those specific monitors?  My HTTP(s) monitors are working however when I create new monitors that do not have data I get an error. 

```
            <?php
              echo "<pre>";
              print_r(json_decode($response, 1));
              echo "</pre>";
            ?>
```

**Comment by HeadTalker** [comment]
I think this should be fixed now.   I added some fallback incase there is not enough data to plot.

https://github.com/HeadTalker/uptime-robot/commit/25de59af3e6226b73358bb0c2ab49bdc5c4337dc

Try updating and see it should be fixed  :+1:

**Comment by HeadTalker** [comment]
I can confirm after inspecting element the arrays were empty since there was no data to process on those last graphs.

It looks like this
```
                  var response_datetime = [];
                  var response_value = [];
```

When it should look like once there is data

```
                  var response_datetime = ["12\/08\/2015 17:05:48","12\/08\/2015 19:05:48","12\/08\/2015 20:56:55","12\/08\/2015 21:59:05"];
                  var response_value = ["266","265","266","250"];
````

So now there is some fallback incase this happens.

**Comment by mritzmann** [comment]
Thank you for your work! :+1:
