### ISSUE TITLE
No Monitors found

### ISSUE THREAD

**Issue by RChrys** [HeadTalker/uptime-robot#7]
I followed the intructions but i've got this result..
![image](https://cloud.githubusercontent.com/assets/19908684/16011609/87355756-3186-11e6-9d86-f21cdb5dd01e.png)
But i've already created some monitors.
![image](https://cloud.githubusercontent.com/assets/19908684/16011650/b3555b24-3186-11e6-9744-5f6b85150908.png)
How can i fix this problem?

**Comment by HeadTalker** [comment]
Did you set your api key in a config.php file?

Do you have Curl enabled?

On Monday, June 13, 2016, RChrys <notifications@github.com> wrote:

> I followed the intructions but i've got this result..
> [image: image]
> <https://cloud.githubusercontent.com/assets/19908684/16011609/87355756-3186-11e6-9d86-f21cdb5dd01e.png>
> But i've already created some monitors.
> [image: image]
> <https://cloud.githubusercontent.com/assets/19908684/16011650/b3555b24-3186-11e6-9744-5f6b85150908.png>
> How can i fix this problem?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/HeadTalker/uptime-robot/issues/7>, or mute the thread
> <https://github.com/notifications/unsubscribe/AI_IGgJePs-lO4qEfq7euvLSStvXvz0tks5qLW3lgaJpZM4I0Z96>
> .
>


-- 

Best Regards,

Chris

Co-Founder

**Comment by RChrys** [comment]
yes i did.
![image](https://cloud.githubusercontent.com/assets/19908684/16033847/b9d07924-320e-11e6-94d6-f0f96f2fb7c8.png)
and Curl is apparently enabled.
![image](https://cloud.githubusercontent.com/assets/19908684/16033869/e58a446e-320e-11e6-9829-be5517e06454.png)

**Comment by HeadTalker** [comment]
Thanks for the images and confirmation.

Can you check your error log and see if there is any errors?  Please paste
the error output if you see any.

Can you see if the api key is being properly set?  Try putting this in
main/index.php on line 33.

<?php var_dump( $UP_ACCOUNT_API_KEY ); ?>

It will spit out some helpful information regarding the variable and
whether it's set.

On Tuesday, June 14, 2016, RChrys <notifications@github.com> wrote:

> yes i did.
> [image: image]
> <https://cloud.githubusercontent.com/assets/19908684/16033847/b9d07924-320e-11e6-94d6-f0f96f2fb7c8.png>
> and Curl is apparently enabled.
> [image: image]
> <https://cloud.githubusercontent.com/assets/19908684/16033869/e58a446e-320e-11e6-9829-be5517e06454.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/HeadTalker/uptime-robot/issues/7#issuecomment-225796580>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AI_IGt7UQYyTnMiUoaxLZ6dQHI8nRw2Cks5qLlJagaJpZM4I0Z96>
> .
>


-- 

Best Regards,

Chris

Co-Founder

**Comment by RChrys** [comment]
![image](https://cloud.githubusercontent.com/assets/19908684/16034426/11eb2caa-3212-11e6-90a9-cc520c14559b.png)
i don't anything special
and i've got this result : 
![image](https://cloud.githubusercontent.com/assets/19908684/16034457/3f456562-3212-11e6-97e7-0dd2934fb9eb.png)

**Comment by RChrys** [comment]
![image](https://cloud.githubusercontent.com/assets/19908684/16034589/e5e1b74a-3212-11e6-8d45-88fcf3085f94.png)
this one will be better i think

**Comment by HeadTalker** [comment]
Okay thanks.  The key is working since it's dumping out like that ( you may
want to generate a new key so no one messes with it ).

The error log is showing some issues.  That's very helpful.  Can you
screenshot more on the right side of the error log or even better dump it
as text here?


On Tuesday, June 14, 2016, RChrys <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/19908684/16034426/11eb2caa-3212-11e6-90a9-cc520c14559b.png>
> i don't anything special
> and i've got this result :
> [image: image]
> <https://cloud.githubusercontent.com/assets/19908684/16034457/3f456562-3212-11e6-97e7-0dd2934fb9eb.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/HeadTalker/uptime-robot/issues/7#issuecomment-225800819>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AI_IGmDeE5Ol2MvcvRnD8wxNgqv3flFSks5qLlfygaJpZM4I0Z96>
> .
>


-- 

Best Regards,

Chris

Co-Founder

**Comment by HeadTalker** [comment]
Thanks.  Did you refactor the file and folder structure?  What is
monitor_report.php ?

On Tuesday, June 14, 2016, Chris LaBonty <chris@headtalker.com> wrote:

> Okay thanks.  The key is working since it's dumping out like that ( you
> may want to generate a new key so no one messes with it ).
>
> The error log is showing some issues.  That's very helpful.  Can you
> screenshot more on the right side of the error log or even better dump it
> as text here?
>
>
> On Tuesday, June 14, 2016, RChrys <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/19908684/16034426/11eb2caa-3212-11e6-90a9-cc520c14559b.png>
>> i don't anything special
>> and i've got this result :
>> [image: image]
>> <https://cloud.githubusercontent.com/assets/19908684/16034457/3f456562-3212-11e6-97e7-0dd2934fb9eb.png>
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/HeadTalker/uptime-robot/issues/7#issuecomment-225800819>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AI_IGmDeE5Ol2MvcvRnD8wxNgqv3flFSks5qLlfygaJpZM4I0Z96>
>> .
>>
>
>
> --
>
> Best Regards,
>
> Chris
>
> Co-Founder
>
>
>
>

-- 

Best Regards,

Chris

Co-Founder

**Comment by RChrys** [comment]
This is another api i tried before. 
I only changed the file config.php as you said.
Today, i only use you api

**Comment by HeadTalker** [comment]
Thanks.  Sorry it's taking so long to figure this out.  Can you show me a
picture of the file manager where the config.php is?
:)


On Tuesday, June 14, 2016, RChrys <notifications@github.com> wrote:

> This is another api i tried before.
> I only changed the file config.php as you said.
> Today, i only use you api
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/HeadTalker/uptime-robot/issues/7#issuecomment-225804321>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AI_IGhp2BABqRh8ykYQ-wqsXl9U4kvNnks5qLlwigaJpZM4I0Z96>
> .
>


-- 

Best Regards,

Chris

Co-Founder

**Comment by RChrys** [comment]
![image](https://cloud.githubusercontent.com/assets/19908684/16035226/51a1df70-3216-11e6-9f8e-783a71b7012f.png)
like this?

**Comment by HeadTalker** [comment]
Everything looks good.

What happens when you try this simple CURL example?

You can make a file called test.php and put this code in it:

```php
<?php

$endpoint = "https://api.uptimerobot.com/getMonitors?apiKey=YOURKEYGOESHERE&responseTimes=1&logs=1&format=json&noJsonCallback=1";
$curl     = curl_init( $endpoint );

curl_setopt_array( $curl, [
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_URL            => $endpoint,
] );

$response         = curl_exec( $curl );
$monitor_response = json_decode( $response, true );

print_r( $monitor_response );

?>
```

Then view the file and see what the response is.  If theres no response then maybe it has something to do with your Windows environment and CURL.  If thats the case take a look at http://stackoverflow.com/questions/10939248/php-curl-not-working-wamp-on-windows-7-64-bit .

**Comment by HeadTalker** [comment]
Hey have you tried the simple example to see if that works?

**Comment by RChrys** [comment]
yes, i follow the instructions and now, i've to install another curl but i don't know how is work..

**Comment by HeadTalker** [comment]
Was there no response when viewing that file?

It looks like your running easy PHP server not WAMP actually.  Maybe this can help:

http://stackoverflow.com/questions/34905939/activation-curl-on-easyphp
http://stackoverflow.com/questions/35113820/easyphp-devserver-16-1-curl-win-10/35135245#35135245

**Comment by HeadTalker** [comment]
Since this seems like an environment issue with CURL I am going to close this.
